datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - 'com.app.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
kafka.bootstrap.servers: localhost:9092

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
