micronaut:
  application:
    name: planningpoker
  server:
    context-path: /planningpoker
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    intercept-url-map:
      - pattern: /**
        access:
          - isAnonymous()

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/planningpoker
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - 'com.app.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
kafka.bootstrap.servers: localhost:9092

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
